CREATE TABLE `USER_DETAILS` (
  `FIRST_NM` varchar(32) NOT NULL,
  `LAST_NM` varchar(45) NOT NULL,
  `N_NUMBER` varchar(9) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `CREATE_USR_ID` varchar(32) DEFAULT 'UNFSC',
  `CREATE_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDT_USR_ID` varchar(45) DEFAULT 'UNFSC',
  `UPDT_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`N_NUMBER`),
  KEY `EMAIL` (`EMAIL`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `PROFILE_DETAILS` (
  `PROFILE_ID` int(6) NOT NULL AUTO_INCREMENT,
  `N_NUMBER` varchar(9) DEFAULT NULL,
  `NAME` varchar(50) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `CONTACT` varchar(25) DEFAULT NULL,
  `SKILLS` varchar(250) DEFAULT NULL,
  `INTERESTS` varchar(250) DEFAULT NULL,
  `LEVEL` varchar(50) NOT NULL,
  `PROGRAM` varchar(150) NOT NULL,
  `START_DATE` date DEFAULT NULL,
  `END_DATE` date DEFAULT NULL,
  `DEPARTMENT` varchar(150) DEFAULT NULL,
  `THESIS_TOPIC` varchar(150) DEFAULT NULL,
  `THESIS_ADVISOR` varchar(100) DEFAULT NULL,
  `COURSES` varchar(150) DEFAULT NULL,
  `COMPANY` varchar(130) DEFAULT NULL,
  `JOB_TITLE` varchar(100) DEFAULT NULL,
  `ROLE` varchar(100) DEFAULT NULL,
  `CREATE_USR_ID` varchar(32) DEFAULT 'UNFSC',
  `CREATE_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDT_USR_ID` varchar(45) DEFAULT 'UNFSC',
  `UPDT_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SEARCH_KEY` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`PROFILE_ID`),
  UNIQUE KEY `profile_details_ak` (`N_NUMBER`),
  UNIQUE KEY `profile_details_unique_ak` (`N_NUMBER`),
  KEY `N_NUMBER` (`N_NUMBER`),
  CONSTRAINT `PROFILE_DETAILS_ibfk_1` FOREIGN KEY (`N_NUMBER`) REFERENCES `USER_DETAILS` (`N_NUMBER`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;


CREATE TABLE `EVENT_DETAILS` (
  `EVENT_ID` int(6) NOT NULL AUTO_INCREMENT,
  `EVENT_OWNER` varchar(50) DEFAULT NULL,
  `EVENT_NAME` varchar(250) NOT NULL,
  `EVENT_DESCRIPTION` varchar(600) DEFAULT NULL,
  `OWNER_CONTACT` varchar(25) DEFAULT NULL,
  `EVENT_TIME` time NOT NULL,
  `CREATE_USR_ID` varchar(32) DEFAULT 'UNFSC',
  `CREATE_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDT_USR_ID` varchar(45) DEFAULT 'UNFSC',
  `UPDT_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EVENT_DURATION` varchar(10) DEFAULT NULL,
  `USER_ID` varchar(9) DEFAULT NULL,
  `LOCATION` varchar(200) DEFAULT NULL,
  `SEARCH_KEY` varchar(1000) DEFAULT NULL,
  `PUBLIC_IND` varchar(3) DEFAULT NULL,
  PRIMARY KEY (`EVENT_ID`),
  KEY `EVENT_OWNER` (`EVENT_OWNER`),
  KEY `USER_ID` (`USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8;


CREATE TABLE `EVENT_SUBSCRIPTION_DETAILS` (
  `SUBSCRIPTION_ID` int(6) NOT NULL AUTO_INCREMENT,
  `EVENT_ID` int(10) DEFAULT NULL,
  `USER_ID` varchar(10) DEFAULT NULL,
  `SUBSCRIPTION_DTS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUBSCRIPTION_ID`),
  KEY `EVENTS_STUDENTID` (`USER_ID`),
  KEY `SUBSCRIPTION_EVENT_ID` (`EVENT_ID`),
  CONSTRAINT `EVENTSSUBSCRIPTION_DETAILS_ibfk_1` FOREIGN KEY (`USER_ID`) REFERENCES `USER_DETAILS` (`N_NUMBER`),
  CONSTRAINT `EVENTSSUBSCRIPTION_DETAILS_ibfk_2` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT_DETAILS` (`EVENT_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;
alter table EVENT_DETAILS add PUBLIC_IND varchar(3);

